# DigitalOcean App Platform Configuration
name: haderos-platform
region: fra
services:
  # Backend API Service
  - name: backend
    github:
      repo: ka364/haderos-platform
      branch: master
      deploy_on_push: true
    
    build_command: pip install -r requirements.txt
    run_command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      
      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: YOUR_SECRET_KEY_HERE
      
      - key: DEBUG
        scope: RUN_TIME
        value: "False"
      
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: "https://haderosai.com,https://www.haderosai.com"
      
      - key: KAIA_SERVICE_URL
        scope: RUN_TIME
        value: "http://localhost:8080"
      
      - key: THEOLOGY_FIREWALL_ENABLED
        scope: RUN_TIME
        value: "true"
    
    http_port: 8000
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
    
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

databases:
  - name: db
    engine: PG
    production: true
    cluster_name: app-0aa8268b-a1c8-4121-ad4e-1fa37780bc7b

domains:
  - domain: haderosai.com
    type: PRIMARY
  - domain: www.haderosai.com
    type: ALIAS

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
