CREATE TABLE `bank_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transaction_date` date NOT NULL,
	`value_date` date NOT NULL,
	`description` text NOT NULL,
	`reference` varchar(100),
	`amount` decimal(12,2) NOT NULL,
	`type` varchar(20) NOT NULL,
	`balance` decimal(12,2),
	`shipping_company` varchar(50),
	`tin` varchar(100),
	`matched` boolean DEFAULT false,
	`matched_shipment_id` int,
	`matched_shipment_type` varchar(20),
	`match_confidence` decimal(5,2),
	`import_batch_id` varchar(100),
	`imported_at` timestamp NOT NULL DEFAULT (now()),
	`imported_by` int,
	`raw_data` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bank_transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bosta_shipments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tracking_number` varchar(100) NOT NULL,
	`business_reference` varchar(100),
	`order_id` int,
	`type` int NOT NULL,
	`package_type` varchar(50) NOT NULL,
	`cod` decimal(10,2),
	`receiver_name` varchar(200) NOT NULL,
	`receiver_phone` varchar(20) NOT NULL,
	`receiver_email` varchar(200),
	`address` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`zone` varchar(100),
	`state` varchar(50) NOT NULL,
	`state_code` int NOT NULL,
	`waybill_url` text,
	`promised_date` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`delivered_at` timestamp,
	`cod_collected` boolean DEFAULT false,
	`cod_collection_date` timestamp,
	`cod_transfer_date` timestamp,
	`cod_transfer_amount` decimal(10,2),
	`raw_response` json,
	CONSTRAINT `bosta_shipments_id` PRIMARY KEY(`id`),
	CONSTRAINT `bosta_shipments_tracking_number_unique` UNIQUE(`tracking_number`)
);
--> statement-breakpoint
CREATE TABLE `bosta_webhook_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tracking_number` varchar(100) NOT NULL,
	`event` varchar(100) NOT NULL,
	`state` varchar(50) NOT NULL,
	`timestamp` timestamp NOT NULL,
	`payload` json NOT NULL,
	`processed` boolean DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bosta_webhook_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cod_matches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bank_transaction_id` int NOT NULL,
	`shipment_type` varchar(20) NOT NULL,
	`shipment_id` int NOT NULL,
	`tracking_number` varchar(100) NOT NULL,
	`match_type` varchar(20) NOT NULL,
	`match_confidence` decimal(5,2),
	`expected_amount` decimal(10,2) NOT NULL,
	`actual_amount` decimal(10,2) NOT NULL,
	`difference` decimal(10,2),
	`status` varchar(20) NOT NULL,
	`notes` text,
	`matched_by` int,
	`matched_at` timestamp NOT NULL DEFAULT (now()),
	`verified_by` int,
	`verified_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cod_matches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `jnt_shipments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bill_code` varchar(100) NOT NULL,
	`txlogistic_id` varchar(100) NOT NULL,
	`order_id` int,
	`pay_type` int NOT NULL,
	`cod_amount` decimal(10,2),
	`weight` decimal(10,2) NOT NULL,
	`goods_type` varchar(100),
	`receiver_name` varchar(200) NOT NULL,
	`receiver_phone` varchar(20) NOT NULL,
	`receiver_mobile` varchar(20),
	`receiver_email` varchar(200),
	`address` text NOT NULL,
	`city` varchar(100) NOT NULL,
	`area` varchar(100),
	`postcode` varchar(20),
	`status` varchar(50) NOT NULL,
	`sorting_code` varchar(100),
	`package_code` varchar(100),
	`waybill_url` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`delivered_at` timestamp,
	`cod_collected` boolean DEFAULT false,
	`cod_collection_date` timestamp,
	`cod_transfer_date` timestamp,
	`cod_transfer_amount` decimal(10,2),
	`raw_response` json,
	`remark` text,
	CONSTRAINT `jnt_shipments_id` PRIMARY KEY(`id`),
	CONSTRAINT `jnt_shipments_bill_code_unique` UNIQUE(`bill_code`)
);
--> statement-breakpoint
CREATE TABLE `jnt_webhook_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bill_code` varchar(100) NOT NULL,
	`event` varchar(100) NOT NULL,
	`scan_type` varchar(50),
	`desc` text,
	`scan_time` timestamp NOT NULL,
	`payload` json NOT NULL,
	`processed` boolean DEFAULT false,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `jnt_webhook_logs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reconciliation_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`period_start` date NOT NULL,
	`period_end` date NOT NULL,
	`shipping_company` varchar(50) NOT NULL,
	`total_shipments` int NOT NULL,
	`total_expected_cod` decimal(12,2) NOT NULL,
	`total_collected_cod` decimal(12,2) NOT NULL,
	`total_matched` int NOT NULL,
	`total_unmatched` int NOT NULL,
	`total_disputed` int NOT NULL,
	`total_difference` decimal(12,2),
	`percentage_matched` decimal(5,2),
	`report_data` json,
	`status` varchar(20) NOT NULL,
	`generated_by` int,
	`generated_at` timestamp NOT NULL DEFAULT (now()),
	`approved_by` int,
	`approved_at` timestamp,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reconciliation_reports_id` PRIMARY KEY(`id`)
);
