import { Sparkles, Zap, AlertTriangle, Lightbulb, TrendingUp } from "lucide-react";
import { Badge } from "@/components/ui/badge";

interface AIInsight {
  type: "recommendation" | "alert" | "tip";
  title: string;
  description: string;
  isAutoGenerated: boolean;
}

interface AIInsightsData {
  currentInsight: AIInsight;
  stats: {
    alerts: number;
    tips: number;
    accuracy: number;
  };
}

export function AIInsightsCard() {
  const data: AIInsightsData = {
    currentInsight: {
      type: "recommendation",
      title: "Restock Product X to Avoid Outage",
      description: "AI analysis predicts stock depletion in 5 days based on current sales velocity. Recommended order: 250 additional units.",
      isAutoGenerated: true,
    },
    stats: {
      alerts: 3,
      tips: 7,
      accuracy: 94,
    },
  };

  return (
    <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-[#1a1a24] to-[#12121a] border border-purple-500/20 p-6 h-full">
      {/* Animated gradient background */}
      <div className="absolute top-0 right-0 w-40 h-40 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-full blur-3xl animate-pulse" />

      {/* Header */}
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500/30 to-pink-500/30 flex items-center justify-center">
          <Sparkles className="w-5 h-5 text-purple-400" />
        </div>
        <div>
          <h3 className="font-semibold text-white">AI Insights</h3>
          <p className="text-xs text-gray-500">DevLab & Guardian AI</p>
        </div>
      </div>

      {/* Current Insight */}
      <div className="relative mb-6">
        <div className="flex items-center gap-2 mb-3">
          <Zap className="w-4 h-4 text-yellow-400" />
          {data.currentInsight.isAutoGenerated && (
            <Badge variant="outline" className="bg-pink-500/20 border-pink-500/30 text-pink-400 text-xs">
              <span className="mr-1">🤖</span> Auto-Generated
            </Badge>
          )}
        </div>

        <div className="bg-gradient-to-br from-purple-900/20 to-pink-900/20 rounded-xl p-4 border border-purple-500/10">
          <h4 className="font-medium text-white mb-2 flex items-center gap-2">
            <Lightbulb className="w-4 h-4 text-yellow-400" />
            Recommendation: {data.currentInsight.title}
          </h4>
          <p className="text-sm text-gray-400 leading-relaxed">
            {data.currentInsight.description}
          </p>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-3 gap-3">
        <div className="bg-white/5 rounded-xl p-3 text-center">
          <div className="flex items-center justify-center gap-1 mb-1">
            <AlertTriangle className="w-3 h-3 text-yellow-400" />
          </div>
          <p className="text-xs text-gray-400">Alerts</p>
          <p className="text-xl font-bold text-white">{data.stats.alerts}</p>
        </div>
        <div className="bg-white/5 rounded-xl p-3 text-center">
          <div className="flex items-center justify-center gap-1 mb-1">
            <Lightbulb className="w-3 h-3 text-blue-400" />
          </div>
          <p className="text-xs text-gray-400">Tips</p>
          <p className="text-xl font-bold text-blue-400">{data.stats.tips}</p>
        </div>
        <div className="bg-white/5 rounded-xl p-3 text-center">
          <div className="flex items-center justify-center gap-1 mb-1">
            <TrendingUp className="w-3 h-3 text-green-400" />
          </div>
          <p className="text-xs text-gray-400">Accuracy</p>
          <p className="text-xl font-bold text-green-400">{data.stats.accuracy}%</p>
        </div>
      </div>
    </div>
  );
}
